#!/bin/bash

tail -f ~/solana.log | awk -v address="$2na3vueUBtYDBy1iHFRsiC1oTj5mfKrHXhjdiNaGQ1AS" '
/'"$address"'.+within slot/ {
    duration=($18-$12)*0.459;
    hours=int(duration/3600);
    minutes=int((duration%3600)/60);
    seconds=int(duration%60);
    printf "%d hr. %d min. %d sec.\n", hours, minutes, seconds;
    if (minutes >= 60) {
        system("sudo fstrim -av") # Запускаем fstrim, когда время достигает 60 минут
    }
}'
